<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>d3-async-await-notes</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
</head>
<body>
<h1 id="modern-promises-with-asyncawait">MODERN PROMISES WITH ASYNC/AWAIT</h1>
<p>Overview - designed to allow JS devs to write true synchronous code</p>
<pre><code>// USING .THEN
// - not very clean

function walkTheDog() {
  return new Promise((resolve, reject) =&gt; {
    setTimeout(() =&gt; {
      resolve(&quot;happy dog&quot;);
    }, 1000);
  });
}

function doChores() {
  console.log(&quot;before walking the dog&quot;);
    walkTheDog()
        .then((res) =&gt; {
            console.log(res);
            console.log(&quot;after walking the dog&quot;);
    });
}

doChores();</code></pre>
<p>Function Declaration with <code>async</code> - creates a function that returns an implicit promise containing the result - allows us to utilize <code>await</code> keyword inside</p>
<p>Awaiting Promises with <code>await</code> - used to wait for promise to be fulfilled or rejected - rest of code in <code>async</code> func waits until promise is fulfilled to execute - can only use inside an <code>async</code> function</p>
<pre><code>// USING ASYNC/AWAIT


function walkTheDog() {
  return new Promise((resolve, reject) =&gt; {
    setTimeout(() =&gt; {
      resolve(&quot;happy dog&quot;);
    }, 1000);
  });
}

async function doChores() {
    console.log(&quot;before walking the dog&quot;);
    const res = await walkTheDog();
    console.log(res);
    console.log(&quot;after walking the dog&quot;);
    return res.toUpperCase();
}


// async funcs return a promise
// return value is value promise fulfills with
// passed along to following .thens
doChores()
    .then(res =&gt; console.log(res))</code></pre>
<p>Error Handling - <code>async</code>/<code>await</code> results in synchronous execution - can use normal <code>try...catch</code> block to handle errors if promise rejected</p>
<pre><code>function action() {
  return new Promise((resolve, reject) =&gt; {
    setTimeout(() =&gt; {
      reject(&#39;uh-oh&#39;); // rejected
    }, 3000);
  });
}

async function handlePromise() {
  try {
    const res = await action();
    console.log(&#39;resolved with&#39;, res);
  } catch (err) {
    console.log(&#39;rejected because of&#39;, err);
  }
}

handlePromise();</code></pre>
</body>
</html>
